##########################################################
###################  开发环境的profile  ###################
##########################################################

###################  项目启动端口  ###################
server:
  port: 8080
###################  spring配置  ###################
spring:
  profiles:
    active: dev
  http:
    converters:
      preferred-json-mapper: fastjson
    multipart:
      max-request-size: 100MB #最大请求大小
      max-file-size: 100MB #最大文件大小
  aop:
    proxy-target-class: true #false为启用jdk默认动态代理,true为cglib动态代理
---
###################  mybatis-plus配置  ###################
mybatis-plus:
  mapper-locations: classpath*:com/yatoooon/managementsystem/**/mapper/*.xml
  typeAliasesPackage: com.yatoooon.managementsystem.model
  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用
##########################################################
###################  开发环境的profile  ###################
##########################################################
spring:
  profiles: dev
  datasource:
      url: jdbc:mysql://localhost:3306/management_system?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
---

##########################################################
###################  正式环境的profile  ###################
##########################################################
spring:
  profiles: dev
  datasource:
      url: jdbc:mysql://localhost:3306/management_system?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: 123456